name: solidtrade
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  logger: ^1.1.0
  get_it: ^7.2.0
  rxdart: ^0.27.3
  skeletons: ^0.0.3
  flutter_svg: ^1.0.3
  enum_to_string: ^2.0.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.12
  cached_network_image: ^3.2.0
  syncfusion_flutter_charts: ^19.4.47

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/images/
