name: solidtrade
description:
  A platform which allows paper trading Stocks, ETFs, Crypto and Derivatives.
  And also allows to view and compare your portfolio with friends and others!
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dart_json_mapper: ^2.2.7
  dotted_line: ^3.1.0
  enum_to_string: ^2.0.1
  firebase_auth: ^4.2.2
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_keyboard_visibility: ^5.4.0
  flutter_svg: ^2.0.2
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  http: ^0.13.5
  image: ^4.0.15
  image_cropper: ^3.0.1
  image_picker: ^0.8.6+4
  intl: ^0.17.0
  local_auth: ^2.1.6
  logger: ^1.2.2
  mime: ^1.0.4
  modal_bottom_sheet: ^2.1.2
  permission_handler: ^10.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.18
  skeletons: ^0.0.3
  stack_trace: ^1.11.0
  syncfusion_flutter_charts: ^20.4.52
  url_launcher: ^6.1.10
  visibility_detector: ^0.3.3
  web_socket_channel: ^2.3.0
  intl_utils: ^2.8.2
  flutter_secure_storage: ^8.0.0
  flutter_localization: ^0.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
