version: "3"

includes:
  api: ../Taskfile.yml

tasks:
  dev:
    cmds:
      - "flutter run -t lib/app/main_dev.dart"

  gen:
    cmds:
      - "flutter pub run build_runner build --delete-conflicting-outputs"

  reset:
    cmds:
      - "flutter clean && flutter pub get"
