version: "3"

tasks:
  gen:
    cmds:
      - "flutter pub run build_runner build --delete-conflicting-outputs"
    silent: true

  reset:
    cmds:
      - "flutter clean && flutter pub get"
    silent: true
