version: "3.9"

services:
  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - api
    environment:
      AUTH_TOKEN: ${NGROK_AUTH_TOKEN}
      REGION: eu
      DOMAIN: api
      PORT: 80
    depends_on:
        - api
  
  api:
    build: server
    ports:
      - ${API_PORT}:80
    env_file:
      - api.env
    depends_on:
      - db
  
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - ${DB_PORT}:1433
    volumes:
      - solidtrade:/var/opt/mssql/data
    environment:
      SA_PASSWORD: ${DB_SA_PASSWORD}
      ACCEPT_EULA: "Y"

volumes:
  solidtrade: 