name: Deploy Production

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on stable branch
      - stable

  pull_request_target:
    branches: stable
    types: [closed]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "."
          target: "/root/projects/SolidTrade/"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd /root/projects/SolidTrade/server
            chmod +x /root/projects/SolidTrade/server/start.sh
            /root/projects/SolidTrade/server/start.sh
