name: Deploy Development

on:
  push:
    branches:
      - '*'
      - '!stable'
      - '!staging'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch
        
      - uses: actions/checkout@v1
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          rm: true
          source: "."
          target: ${{ format('{0}-{1}/', '/root/projects/SolidTrade', steps.extract_branch.outputs.branch) }}

      - name: Run applications
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            echo "test"
            for var in "$@"
            do
              echo "$var"
            done
            echo "exit"
            exit 0
            echo "__"
            cd /root/projects/SolidTrade-$BRANCH/
            chmod +x ./run.sh
            ./run.sh $BRANCH
